apiVersion: v1
kind: Service
metadata:
  name: task-backend-service
  namespace: dev
spec:
  selector:
    app: task-backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30500
  type: NodePort
